//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carubbi.ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStock
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OperationDate { get; set; }
        public bool Direction { get; set; }
        public int ProductId { get; set; }
        public int AcademyId { get; set; }
    
        public virtual Academies Academies { get; set; }
        public virtual Products Products { get; set; }
    }
}
